spring.application.name=com.ecommerce
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#jwt.secret = ecommerceSecretKey12397845213232

jwt.expirationMs = 250000
